In [1]:
import cv2 as cv

img = cv.imread("data/sex.jpg")

In [2]:
print(img)

[[[255 255 246]
  [253 255 246]
  [255 255 252]
  ...
  [253 251 255]
  [255 253 255]
  [253 254 255]]

 [[255 255 255]
  [254 253 255]
  [253 252 255]
  ...
  [246 246 252]
  [248 248 254]
  [252 253 255]]

 [[252 246 255]
  [195 190 217]
  [150 145 176]
  ...
  [116 119 124]
  [108 111 116]
  [104 107 112]]

 ...

 [[255 255 249]
  [153 154 145]
  [152 153 144]
  ...
  [157 154 146]
  [152 149 141]
  [154 151 143]]

 [[255 255 251]
  [153 153 147]
  [152 152 146]
  ...
  [149 147 139]
  [150 148 140]
  [154 152 144]]

 [[255 255 251]
  [153 153 147]
  [152 152 146]
  ...
  [150 148 140]
  [151 149 141]
  [155 153 145]]]


In [3]:
print(type(img)) 

<class 'numpy.ndarray'>


In [4]:
print(img.shape)

(402, 401, 3)
